repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # error with black on windows?
  # https://lifesaver.codes/answer/pre-commit-hook-with-black-1046
  # - repo: https://github.com/psf/black
  #   rev: 21.12b0
  #   hooks:
  #     - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    name: flake8
    rev: v1.2.3
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
